
import Footer from "./components/Footer";
import NavBar from "./components/NavBar";
import "./globals.css";



export const metadata = {
  title: "Joy Stick Repair",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body suppressHydrationWarning={true}>     
       <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
